"""added foreign key field nullable and optional in model

Revision ID: a42c3248e2f0
Revises: a8fbd8e5fee6
Create Date: 2024-09-01 18:09:05.344479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a42c3248e2f0'
down_revision: Union[str, None] = 'a8fbd8e5fee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'designation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'designation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
