"""Added relationship

Revision ID: a8fbd8e5fee6
Revises: 506424da544b
Create Date: 2024-09-01 17:40:33.154940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8fbd8e5fee6'
down_revision: Union[str, None] = '506424da544b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('designation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('employee', sa.Column('designation_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employee', 'designation', ['designation_id'], ['id'])
    op.drop_column('employee', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('designation', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'designation_id')
    op.alter_column('designation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
